#pragma once
#include "F4SE/F4SE.hpp"
#include "RE/A/ACTOR_LIFE_STATE.hpp"
#include "RE/B/ButtonEvent.hpp"
#include "RE/D/DEFAULT_OBJECT.hpp"
#include "RE/G/GUN_STATE.hpp"
#include "RE/M/MenuOpenCloseEvent.hpp"
#include "RE/N/NiNode.hpp"
#include "RE/P/PlayerCamera.hpp"
#include "RE/P/PlayerCharacter.hpp"
#include "RE/P/PlayerControls.hpp"
#include "RE/P/PlayerInputHandler.hpp"
#include "RE/S/Setting.hpp"
#include "RE/S/SettingUtil.hpp"
#include "RE/T/ThirdPersonState.hpp"
#include "RE/U/UI.hpp"
#include "RE/W/WEAPON_STATE.hpp"
#include <Windows.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cwctype>
#include <filesystem>
#include <numbers>
#include <optional>
#include <utility>
